# Generated by Django 5.1.5 on 2025-01-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_patientdb_diagnosisdb_delete_analysisreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosisdb',
            old_name='patient',
            new_name='cat_id',
        ),
    ]
