# Generated by Django 5.1.5 on 2025-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(help_text='고양이 식별 ID', max_length=50)),
                ('name', models.CharField(help_text='고양이 이름', max_length=100)),
                ('breed', models.CharField(help_text='품종', max_length=100)),
                ('age', models.PositiveIntegerField(default=0, help_text='고양이 나이')),
                ('diagnosis', models.CharField(help_text="'Normal' or 'HCM'", max_length=10)),
                ('diagnosed_at', models.DateField(help_text='진단일(YYYY-MM-DD)')),
            ],
        ),
    ]
